name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    env:
      PUSH: ${{ github.event_name != 'pull_request' }}

    steps:
    - uses: actions/checkout@v2

    - name: get tag
      id: tag
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: log into dockerhub
      if: ${{ env.PUSH == 'true' }}
      uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
      with:
        username: novas0x2a
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: log into ghcr
      if: ${{ env.PUSH == 'true' }}
      uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build (push=${{ env.PUSH }}, tag=${{ steps.tag.outputs.sha8 }})
      uses: docker/build-push-action@v2
      with:
        push: ${{ env.PUSH == 'true' }}
        load: ${{ env.PUSH != 'true' }}
        platforms: linux/amd64
        tags: |
          novas0x2a/debug:${{ steps.tag.outputs.sha8 }}
          novas0x2a/debug:latest
          ghcr.io/novas0x2a/debug:${{ steps.tag.outputs.sha8 }}
          ghcr.io/novas0x2a/debug:latest
